version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: jpa
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bookstore-jpa
    ports:
      - "5445:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
